# Generated by Django 2.2.4 on 2019-08-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
