# Generated by Django 2.2.4 on 2019-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty', to='doctor.Specialty', verbose_name='Specialty'),
        ),
    ]
