# Generated by Django 2.2.4 on 2019-08-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorprofile_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='specialty',
            name='doctor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorProfile'),
            preserve_default=False,
        ),
    ]
