# Generated by Django 2.2.4 on 2019-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190826_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty', to='doctor.Specialty', verbose_name='Specialty'),
        ),
    ]
