# Generated by Django 2.2.4 on 2019-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190826_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('All', 'all'), ('Male', 'male'), ('Female', 'female')], default='All', max_length=6),
        ),
    ]
